### PR TITLE
Assignment #1: Save and Continue

### PR DESCRIPTION
**Pull request by rlankhorst**

### CODE REVIEW

**Comment by AertHulsebos** [comment]
1) [really-simple-ssl/Menu.js at 63bc607f9195ea387439680f4e522df812c324a9 · Really-Simple-Plugins/really-simple-ssl](https://github.com/Really-Simple-Plugins/really-simple-ssl/blob/63bc607f9195ea387439680f4e522df812c324a9/settings/src/Menu.js#L51)
This line the href={href} has been removed. But the href is used to make the URL persistent, allowing for direct URL's to a menu page and refreshes of the loaded page. It should not be removed.

2) The continue is now based on steps. Originally I built in steps in the config, more or less copied over form Complianz. I recently realised this is now obsolete: we can look at the menu array instead, and use that for the next/previous buttons. This removes the necessity to maintain the steps order in the config.

This is why I described the save and continue logic differently from how you now implemented it. Instead of looking at the steps, the logic in react should check what the next menu item is in the menu array that has visible fields. The fields have their own client side react condition logic to decide if it should be available or not. The updateFieldsListWithConditions function handles this, and makes sure that fields are removed from the state if the condition returns false. This means you can use the current field property to check if a menu item has any fields or not.

If there is a main menu with submenus, the main menu should show first, then it should show in order all submenu's. After the last submenu, the first next main menu should be shown.

**Comment by NarKarapetyan93** [comment]
@AertHulsebos @hesseldj I have pushed my changes with now submenus are working too, and the wizard working via URLs not steps :)

**Review by hesseldj — APPROVED** [review]
Looks good @NarKarapetyan93

**Comment by rlankhorst** [comment]
@NarKarapetyan93 @AertHulsebos great solution with the URL's. One more thing: there is currently no check if the menu actually have active content (fields). To illustrate I have pushed some additional fields: one with a react condition, and one with a server side condition. 

If you set "Disable application passwords" to false, and SSL is not enabled, both conditions return false, in which case the two menu items are empty, so should not show after /wp-admin/options-general.php?page=rlrsssl_really_simple_ssl#settings/application_passwords

- The server side condition can be handled in PHP: I think most logical would be before this line: https://github.com/Really-Simple-Plugins/really-simple-ssl/blob/9e4d23d9314a75bf3736d2bd3d2c59dc78912bdf/settings/settings.php#L375  
It only should check for each menu item if there is at least one field/setting connected to it. If not, it can be removed from the array. 

-  The react condition should be checked in react. But it's essentially the same. If there is currently no field connected to this menu, the menu should be dropped. On each state change, the updateFieldsListWithConditions removes fields for which the conditions do not apply. If that happens, and a menu is now empty, the menu should also get removed from the menu array. Until the condition reverses again of course.

**Comment by NarKarapetyan93** [comment]
@rlankhorst so we need to check if the menu item has fields, if yes then check if that field meets the server side conditions then we are keeping that item, if not we are removing it from the menu_items array, and if menu_item doesn't have any field again remove it, right?

**Comment by rlankhorst** [comment]
On the server side: The server side conditions are already checked for each field, so we only need to check if there is at least one field linked to a menu_id

**Comment by NarKarapetyan93** [comment]
@rlankhorst I just pushed save and continue menu items filtering

**Comment by rlankhorst** [comment]
@NarKarapetyan93 Sorry for my late response :). The server side condition now works nicely. Only the client side condition, which should result in showing "Placeholder Setting" in the "Disable code execution in uploads folder" menu below "Hardening", does not respond to enabling/disabling the "disable password applications" setting, which is a condition I have added to that field. The field list gets updated, as you can see the field disappearing, but the menu doesn't update. When working correctly, the menu "Disable code execution in uploads folder" should appear and disappear, in response to the state of the fields list.

**Comment by rlankhorst** [comment]
@NarKarapetyan93 thanks for the update, I see it works now as expected. Only I'm not sure why the 'visible' property is used on the server side. The property is set in the config.php, but it is always true the there, only to become false on the client side if a react condition returns false. I would prefer to add this property on the client side only,  to keep the server side config clean.

**Comment by NarKarapetyan93** [comment]
@rlankhorst I pushed and thought about that now I'm changing it to client-side

**Pull request merged**
